Arewa Data Science Academy
Deep Learning Cohort2.0
Name: Tanimu Abdullahi
Email: aaltanim@gmail.com
Title: Week 1 Solution
Exercises Solution


In [2]:
# Solution 2 a
import torch
torch.__version__
touch_r=torch.rand(size=(7,7))
touch_r.shape

torch.Size([7, 7])

In [3]:
# solution 3
touch_r1=torch.rand(size=(1,7))
touch_r1
mult=torch.matmul(touch_r,touch_r1.T)
mult.shape

torch.Size([7, 1])

In [4]:
# Solution 4
RANDOM_SEED=0 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
touch_r= torch.rand(size=(7, 7))
touch_r1=torch.rand(size=(1,7))
mult=torch.matmul(touch_r,touch_r1.T)
mult

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [12]:
# Solution 5
import torch
torch.cuda.is_available()
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
RANDOM_SEED=1234 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 

In [13]:
# Solution 6
import torch
torch.cuda.is_available()
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
RANDOM_SEED=1234 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
touch_a= torch.rand(size=(2, 3))
touch_b=torch.rand(size=(2,3))
y=touch_a.to(device)
z=touch_b.to(device)
#mult=torch.matmul(touch_r,touch_r1.T)
y,z

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [14]:
# Solution 7
mult1=torch.matmul(touch_a,touch_b.T)
mult1
mult1.shape
mult1

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [8]:
# Solution 8
a=torch.max(mult1)
b=torch.min(mult1)
a, b

(tensor(0.5617), tensor(0.3647))

In [9]:
# Solution 9
h=mult1.argmax()
j=mult1.argmin()
print(h,j)

tensor(3) tensor(0)


In [10]:
# Solution 10
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
tensor3 = torch.rand(size=(1, 1, 1, 10))

# Remove all the 1 dimensions
tensor4 = tensor3.squeeze()

# Print out the first tensor and its shap
print(tensor3, tensor3.shape)

# Print out the second tensor and its shape
print(tensor4, tensor4.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
